% Define the drinking water standards
function standards = define_standards()
    standards = struct('pH', [6.5, 8.5], 'turbidity', 1, 'tds', 500, ...
                       'hardness', 200, 'sulphates', 200, ...
                       'bod', 5, 'cod', 10, 'do', [6.5, 8], ...
                       'nitrate', 10, 'alkalinity', 200);
end
